language: node_js
node_js:
  - "stable"
install:
  - npm install
cache:
  directories:
  - node_modules  

services:
    - postgresql

env:
  global:
  - URL=http://localhost:5000
  - PORT=5000

addons:
    postgresql: '9.6'
    
before_script:
  - psql -c 'create database freementor;' -U yusuf
script:
  - npm run test
after_success:
  - npm run coverage