language: node_js
node_js:
  - "stable"
install:
  - npm install
cache:
  directories:
  - node_modules  
before_script:
  - psql -c 'create database freementor;' -U yusuf
script:
  - npm run test
after_success:
  - npm run coverage