language: node_js
node_js:
  - "stable"
install:
  - yarn install
cache:
  directories:
  - node_modules  

services:
    - postgresql

addons:
    postgresql: '9.6'
    
before_script:
  - psql -c 'create database freementor;' -U yusuf
script:
  - yarn run test
after_success:
  - yarn run coverage