# Sign Up
POST  http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
   "firstName": "Yusuf",
    "lastName": "Mboni",
    "email": "Mbonigabay@gmail.com",
    "password": "123456",
    "address": "kicukiro",
    "bio": "tokdddd",
    "occupation": "Fashion Design",
    "expertise": "Fashion Design",
    "avatar": "sssss",
    "role_id": "2"
}

###
POST https://free-mentor-four.herokuapp.com/api/v1/auth/signup
Content-Type: application/json

{
   "firstName": "Yusuf",
    "lastName": "Mboni",
    "email": "Mbonigabay@gmail.com",
    "password": "123456",
    "address": "kicukiro",
    "bio": "",
    "occupation": "Fashion Design",
    "expertise": "Fashion Design",
    "avatar": "",
    "role_id": "2"
}

# Sign in
###
POST  http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "123456"
}

# View all mentors
###
GET http://localhost:5000/api/v1/mentors
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJCb2IiLCJsYXN0TmFtZSI6IldpbGxpYW1zIiwiZW1haWwiOiJib2JAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkRzFXYVhOT2wxVFVsU0tMNHhNc09BZUs2M0RWb0dCbFVSR0w1T0dtc0lzVHRtdG9NeU9zcUsiLCJhZGRyZXNzIjoiTnlhcnVnZW5nZSIsImJpbyI6IiIsIm9jY3VwYXRpb24iOiJTb2Z0d2FyZSBFbmdpbmVlcmluZyIsImV4cGVydGlzZSI6IlNvZnR3YXJlIEVuZ2luZWVyaW5nIiwiYXZhdGFyIjoiIiwicm9sZV9pZCI6IjEifSwiaWF0IjoxNTY3NTEwODM4fQ.Ek9uh75Ina2_VRrGETVVUinBBq0OWOLaZWImHGz_Etk

# View a mentor
###
GET http://localhost:5000/api/v1/mentors/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJCb2IiLCJsYXN0TmFtZSI6IldpbGxpYW1zIiwiZW1haWwiOiJib2JAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkRzFXYVhOT2wxVFVsU0tMNHhNc09BZUs2M0RWb0dCbFVSR0w1T0dtc0lzVHRtdG9NeU9zcUsiLCJhZGRyZXNzIjoiTnlhcnVnZW5nZSIsImJpbyI6IiIsIm9jY3VwYXRpb24iOiJTb2Z0d2FyZSBFbmdpbmVlcmluZyIsImV4cGVydGlzZSI6IlNvZnR3YXJlIEVuZ2luZWVyaW5nIiwiYXZhdGFyIjoiIiwicm9sZV9pZCI6IjEifSwiaWF0IjoxNTY3NTEwODM4fQ.Ek9uh75Ina2_VRrGETVVUinBBq0OWOLaZWImHGz_Etk

# Create a session
###
POST  http://localhost:5000/api/v1/sessions
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJCb2IiLCJsYXN0TmFtZSI6IldpbGxpYW1zIiwiZW1haWwiOiJib2JAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkRzFXYVhOT2wxVFVsU0tMNHhNc09BZUs2M0RWb0dCbFVSR0w1T0dtc0lzVHRtdG9NeU9zcUsiLCJhZGRyZXNzIjoiTnlhcnVnZW5nZSIsImJpbyI6IiIsIm9jY3VwYXRpb24iOiJTb2Z0d2FyZSBFbmdpbmVlcmluZyIsImV4cGVydGlzZSI6IlNvZnR3YXJlIEVuZ2luZWVyaW5nIiwiYXZhdGFyIjoiIiwicm9sZV9pZCI6IjEifSwiaWF0IjoxNTY3NTEwODM4fQ.Ek9uh75Ina2_VRrGETVVUinBBq0OWOLaZWImHGz_Etk

{
   "mentorId": 1,
    "menteeId": 2,
    "question": "What",
    "menteeEmail": ""
}

# Accept a Session
###
PATCH   http://localhost:5000/api/v1/sessions/1/accept
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJCb2IiLCJsYXN0TmFtZSI6IldpbGxpYW1zIiwiZW1haWwiOiJib2JAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkRzFXYVhOT2wxVFVsU0tMNHhNc09BZUs2M0RWb0dCbFVSR0w1T0dtc0lzVHRtdG9NeU9zcUsiLCJhZGRyZXNzIjoiTnlhcnVnZW5nZSIsImJpbyI6IiIsIm9jY3VwYXRpb24iOiJTb2Z0d2FyZSBFbmdpbmVlcmluZyIsImV4cGVydGlzZSI6IlNvZnR3YXJlIEVuZ2luZWVyaW5nIiwiYXZhdGFyIjoiIiwicm9sZV9pZCI6IjEifSwiaWF0IjoxNTY3NTEwODM4fQ.Ek9uh75Ina2_VRrGETVVUinBBq0OWOLaZWImHGz_Etk

# Reject a Session
###
PATCH   http://localhost:5000/api/v1/sessions/3/reject
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJCb2IiLCJsYXN0TmFtZSI6IldpbGxpYW1zIiwiZW1haWwiOiJib2JAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkRzFXYVhOT2wxVFVsU0tMNHhNc09BZUs2M0RWb0dCbFVSR0w1T0dtc0lzVHRtdG9NeU9zcUsiLCJhZGRyZXNzIjoiTnlhcnVnZW5nZSIsImJpbyI6IiIsIm9jY3VwYXRpb24iOiJTb2Z0d2FyZSBFbmdpbmVlcmluZyIsImV4cGVydGlzZSI6IlNvZnR3YXJlIEVuZ2luZWVyaW5nIiwiYXZhdGFyIjoiIiwicm9sZV9pZCI6IjEifSwiaWF0IjoxNTY3NTEwODM4fQ.Ek9uh75Ina2_VRrGETVVUinBBq0OWOLaZWImHGz_Etk