# Get all users

GET http://localhost:5000

# Sign Up
###
POST   http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
   "firstName": "user",
    "lastName": "one",
    "email": "user3@gmail.com",
    "password": "123456",
    "address": "kicukiro",
    "bio": "tokdddd",
    "occupation": "Fashion Design",
    "expertise": "Fashion Design",
    "avatar": "sssss",
    "role_id": "3"
}

# Sign in
###
POST  http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
    "email": "user3@gmail.com",
    "password": "123456"
}

# View all mentors
###
GET http://localhost:5000/api/v1/mentors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1MUBnbWFpbC5jb20iLCJpYXQiOjE1NjgwMTExMzJ9.sJFiIoQwyy3lKzVpEoQ0-s8lOpzVBC0ukiYbzxYTJBU

# View a mentor
###
GET http://localhost:5000/api/v1/mentors/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1MUBnbWFpbC5jb20iLCJpYXQiOjE1NjgwMTExMzJ9.sJFiIoQwyy3lKzVpEoQ0-s8lOpzVBC0ukiYbzxYTJBU

# Change role
###
PATCH  http://localhost:5000/api/v1/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1MUBnbWFpbC5jb20iLCJpYXQiOjE1NjgwMTExMzJ9.sJFiIoQwyy3lKzVpEoQ0-s8lOpzVBC0ukiYbzxYTJBU

# Create a session
###
POST  http://localhost:5000/api/v1/sessions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1MUBnbWFpbC5jb20iLCJpYXQiOjE1NjgwMTExMzJ9.sJFiIoQwyy3lKzVpEoQ0-s8lOpzVBC0ukiYbzxYTJBU

{
   "mentorId": 16,
    "menteeId": 17,
    "question": "What ARE YOU",
    "menteeEmail": "yusuf@gmail.com"
}

# Accept a Session
###
PATCH   http://localhost:5000/api/v1/sessions/2/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1MUBnbWFpbC5jb20iLCJpYXQiOjE1NjgwMTExMzJ9.sJFiIoQwyy3lKzVpEoQ0-s8lOpzVBC0ukiYbzxYTJBU

# Reject a Session
###
PATCH   http://localhost:5000/api/v1/sessions/2/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1MUBnbWFpbC5jb20iLCJpYXQiOjE1NjgwMTExMzJ9.sJFiIoQwyy3lKzVpEoQ0-s8lOpzVBC0ukiYbzxYTJBU